Enable hand bone received.
sh-akira/VirtualMotionCapture pull request #74
Opened 2021-03-21 16:44 UTC by daifuk-lana

手（手首、指）のボーン受信機能、そのオンオフ機能を追加しました。
諸々実装が怪しい箇所はあるかと思いますが、特に外部からボーンを受信した場合の手首の角度ずれを吸収する機能の実装が正しいか、ご確認頂ければと思います。

2021-03-21 17:26 UTC, sh-akira requested changes
動作的には問題ないはずです。ありがとうございます。
このまま取り込み出来ない部分にコメント入れたので変えてもらえると助かります 🙏

2021-03-21 17:26 UTC, sh-akira commented on Assets/ExternalSender/ExternalReceiverForVMC.cs
> +//ここから追加
ここから～ここまでコメントを消しておいてもらえると助かります(残ってたら後で消します)

2021-03-21 17:26 UTC, sh-akira commented on Assets/ExternalSender/ExternalReceiverForVMC.cs
> +                //追加
ここのコメントアウトも消しちゃって大丈夫です

2021-03-21 17:26 UTC, sh-akira commented on Assets/ExternalSender/ExternalReceiverForVMC.cs
> +        if(receiveBonesFlag)
ここの追加分だけLateUpdateにして他の部分はUpdateのままに出来たら変えてほしいです（他の部分の再検証が必要になるため）

2021-03-21 17:26 UTC, sh-akira commented on Assets/ExternalSender/ExternalReceiverForVMC.cs
> +                }
ここの左手ボーンと右手ボーンの処理が全く同じなのでひとまとめにして
```csharp
                if (bone == HumanBodyBones.LeftHand || bone == HumanBodyBones.RightHand)
                {
                    //ローカル座標系の回転打ち消し
                    Quaternion allLocalRotation = Quaternion.identity;
                    targetTransform = animator.GetBoneTransform(bone);
                    tempTransform = targetTransform;
                    while (tempTransform != hipBone)
                    {
                        tempTransform = tempTransform.parent;
                        //後から逆回転をかけて打ち消し
                        allLocalRotation = allLocalRotation * Quaternion.Inverse(tempTransform.localRotation);
                    }
                    Quaternion receivedRotation = allLocalRotation * rot;
                    //外部からのボーンへの反映
                    BoneSynchronizeSingle(t, ref bone, ref pos, ref receivedRotation);
                }
```
こうすると良い感じっぽいです(後々手以外も対応できそう)

2021-03-21 17:26 UTC, sh-akira commented on Assets/Scenes/VirtualMotionCapture.unity
> +  m_IsActive: 0
これ多分FreeCameraを無効にしたやつかな。動いてればこのままでOK

2021-03-21 17:26 UTC, sh-akira commented on Assets/Scenes/VirtualMotionCapture.unity
> -  controlWPFWindow: {fileID: 1407685704}
ここはDMMVRConnectの設定（僕にしか設定できないのでこのままで良いです）

2021-03-21 17:26 UTC, sh-akira commented on Assets/Scenes/VirtualMotionCapture.unity
> +  m_IsActive: 1
こっちは逆にFrontCameraの有効（動いてればこのままでOK）

2021-03-21 17:26 UTC, sh-akira commented on Assets/Scenes/VirtualMotionCapture.unity
> +  VersionString: v0.49_HI5
VersionStringのfXrXbXの形式はビルド時に無料版FANBOX版ベータ版のバージョン指定に使用しているのでとりあえずf3r3b4に戻しておいてもらえると助かります

2021-03-21 17:26 UTC, sh-akira commented on Assets/Scenes/VirtualMotionCapture.unity
> +  stopNaNPropagation: 0
これControlCameraについてる多分ポスプロの設定？だと思うけどなんだろう

2021-03-21 17:26 UTC, sh-akira commented on Assets/Scenes/VirtualMotionCapture.unity
> +  m_ShowCustomSorter: 1
こっちもポスプロっぽいけどなんだろう

2021-03-21 17:26 UTC, sh-akira commented on Assets/Scenes/VirtualMotionCapture.unity
> -  sdkConfiguration: {fileID: 11400000, guid: dd276808621df4e2380660ade912baf3, type: 2}
これはVRoid SDKの設定（これも僕にしか設定できないのでこのままで良いです）

2021-03-21 17:26 UTC, sh-akira commented on Assets/Scripts/ControlWPFWindow.cs
> +        WaitOneFrameAction(() => CameraChangedAction?.Invoke(ControlCamera));
この二つのWaitOneFrameActionはExternalReceiverを有効にしたときにモデルデータを再読み込みするためのイベントなので消しちゃって大丈夫だと思います。

2021-03-21 17:26 UTC, sh-akira commented on ControlWindowWPF/ControlWindowWPF/Resources/English.xaml
> +    <system:String x:Key="SettingWindow_ReceiveBonesEnable">Hand bone reception</system:String>
Receive hand boneとどっちが良いかな

2021-03-22 03:19 UTC, daifuk-lana commented
ご確認、ありがとうございます！各指摘箇所について修正しました。
コードのプルリクをしたことがないのでこれで正しいか分かりませんが、pushしたものが見られないなどあればお知らせ下さい！

2021-03-22 03:30 UTC, sh-akira approved these changes
修正ありがとうございます！全て問題ありません。
折を見て次のリリース前にマージしたいと思います

2021-03-31 14:11 UTC, merged