CameraPlus 6.0.0以降のjson形式の読み込みを追加
sh-akira/VirtualMotionCapture pull request #81
Opened 2021-07-24 13:18 UTC by Snow1226

お世話になっております。
今後のBSIPAの変更を見込んでCameraPlusの設定ファイルをjson形式に変更したため、
VMCへの読み込み部分にjson形式を追加しました。
プロパティクラスの置き場所が直近になってしまっていますので動かした方がよければお知らせください。

2021-07-28 17:37 UTC, sh-akira requested changes
レビュー遅くなってすみません。いくつか修正をお願いしたいです

2021-07-28 17:37 UTC, sh-akira commented on ControlWindowWPF/ControlWindowWPF/SettingWindow.xaml.cs
> +        [DataContract]
[DataContract]属性と[DataMember]属性無しでデシリアライズできた気がするのでもし外しても動いたら冗長なので消したいです

2021-07-28 17:37 UTC, sh-akira commented on ControlWindowWPF/ControlWindowWPF/SettingWindow.xaml.cs
> +            public TransformElements ThirdPersonPos = new TransformElements();
ここ{ get; set; }でなくnewしないとまずいですか

2021-07-28 17:37 UTC, sh-akira commented on ControlWindowWPF/ControlWindowWPF/SettingWindow.xaml.cs
> +                if (ofd.FileName.ToLower().Contains(".json"))
拡張子なので `if (Path.GetExtension(ofd.FileName) == ".json")`としたいです

2021-07-28 17:37 UTC, sh-akira commented on ControlWindowWPF/ControlWindowWPF/SettingWindow.xaml.cs
> +                        c = (CameraPlusConfig)serializer.ReadObject(ms);
DataContractJsonSerializerの扱いはJsonSerializer.csに一任しているので、ここは
```csharp
var json = File.ReadAllText(ofd.FileName);
var c = Json.Serializer.Deserialize<CameraPlusConfig>(json);
```
としてほしいです

2021-07-29 12:15 UTC, Snow1226 reviewed
ご指摘いただいた箇所について、修正を行いました。
よろしくお願いいたします。

2021-07-29 12:15 UTC, Snow1226 commented on ControlWindowWPF/ControlWindowWPF/SettingWindow.xaml.cs
> +        [DataContract]
System.Runtime.Serialization.Jsonの場合、属性無しでデシリアライズができなかったため残ってしまいました。

2021-07-29 12:15 UTC, Snow1226 commented on ControlWindowWPF/ControlWindowWPF/SettingWindow.xaml.cs
> +            public TransformElements ThirdPersonPos = new TransformElements();
{ get; set; }でよかったですね、修正いたしました。

2021-07-29 12:15 UTC, Snow1226 commented on ControlWindowWPF/ControlWindowWPF/SettingWindow.xaml.cs
> +                if (ofd.FileName.ToLower().Contains(".json"))
失礼致しました、訂正しました。

2021-07-29 12:15 UTC, Snow1226 commented on ControlWindowWPF/ControlWindowWPF/SettingWindow.xaml.cs
> +                        c = (CameraPlusConfig)serializer.ReadObject(ms);
該当箇所修正いたしました。

2021-07-29 12:20 UTC, sh-akira approved these changes

2021-07-29 12:24 UTC, merged